import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@repo/ui/globals.css";
import { Providers } from "@/components/providers";
import AppSidebar from "@/components/app-sidebar";
import React from "react";

import { SidebarProvider } from "@repo/ui/components/sidebar";
import {
  USER_ROLE,
  ADMIN_PAGE_LINKS,
  USER_PAGE_LINKS,
} from "@/constants/constants";

const fontSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAdmin = USER_ROLE === "admin";
  const sidebarLinks = isAdmin ? ADMIN_PAGE_LINKS : USER_PAGE_LINKS;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased `}
      >
        <Providers>
          <SidebarProvider>
            <AppSidebar items={sidebarLinks} />
            <main className="w-full pb-16">{children}</main>
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
