import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@repo/ui/globals.css";
import { Providers } from "@/components/providers";
import AppSidebar from "@repo/ui/components/app-sidebar";
import React from "react";

import { SidebarProvider } from "@repo/ui/components/sidebar";
import { USER_PAGE_LINKS } from "@repo/ui/constants/contants";

const fontSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased `}
      >
        <Providers>
          <SidebarProvider>
            <AppSidebar items={USER_PAGE_LINKS} />
            {children}
          </SidebarProvider>
        </Providers>
      </body>
    </html>
  );
}
