import type { Metadata } from "next";
import "@repo/ui/globals.css";
import AppSidebar from "@/components/app-sidebar";
import React from "react";

import { SidebarProvider } from "@repo/ui/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="w-full pb-16">{children}</main>
    </SidebarProvider>
  );
}
