name: Check types and unit tests

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4

      # Install pnpm and dependencies
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0
          run_install: true

      # Install Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # Check types and unit tests
      - name: Check types and unit tests
        run: |
          pnpm run check-types
          pnpm run test
